version: "3.8"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - SERVICES=acm,apigateway,cloudformation,cloudwatch,dynamodb,ec2,es,firehose,iam,kinesis,kms,lambda,logs,rds,redshift,route53,s3,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - CORS="http://localhost:3000" # NUEVA LÍNEA: Permite CORS solo desde tu app React
      # Si por alguna razón "http://localhost:3000" no funciona, puedes intentar con un comodín
      # - CORS="*" # Opcional: Para permitir desde cualquier origen (menos seguro, pero útil para depuración extrema)
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s